import { Project, CadastralParcel, Objection, Award } from "@/lib/types/schema";

export const SEED_PROJECTS: Project[] = [
  {
    id: "NH-44-DELHI-AMRITSAR",
    name: "NH-44 Delhi-Amritsar National Land Acquisition",
    ministry: "Ministry of Road Transport & Highways / MoRTH",
    corridorType: "PM GatiShakti Integrated",
    currentStage: 2,
    activeCorridorsCount: 14,
    totalDisbursedCrores: 1420,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "DME-PKG-04-DELHI-MUMBAI",
    name: "Delhi-Mumbai Expressway (Package 4)",
    ministry: "Ministry of Road Transport & Highways / MoRTH",
    corridorType: "Expressway",
    currentStage: 1,
    activeCorridorsCount: 8,
    totalDisbursedCrores: 350,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "DFC-EASTERN-CORRIDOR",
    name: "Eastern Dedicated Freight Corridor",
    ministry: "Ministry of Railways",
    corridorType: "Railways",
    currentStage: 4,
    activeCorridorsCount: 22,
    totalDisbursedCrores: 4850,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "MAHSR-BULLET-TRAIN",
    name: "Mumbai-Ahmedabad High Speed Rail (MAHSR)",
    ministry: "Ministry of Railways",
    corridorType: "High Speed Rail",
    currentStage: 5,
    activeCorridorsCount: 12,
    totalDisbursedCrores: 8200,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "BENGALURU-SUBURBAN-RAIL",
    name: "Bengaluru Suburban Rail Project (BSRP)",
    ministry: "Ministry of Railways / K-RIDE",
    corridorType: "Suburban Rail",
    currentStage: 3,
    activeCorridorsCount: 4,
    totalDisbursedCrores: 120,
    updatedAt: new Date().toISOString(),
  }
];

export const SEED_PARCELS: CadastralParcel[] = [
  {
    id: "KHASRA-142-3-1",
    projectId: "NH-44-DELHI-AMRITSAR",
    khasraNo: "142/3/1",
    ownerName: "Sardar Gurdeep Singh Sandhu",
    village: "Kartarpur",
    tehsil: "Jalandhar-II",
    district: "Jalandhar",
    state: "Punjab",
    areaHectares: 1.45,
    multiplier: 1.5,
    possessionStatus: "Possession Handed Over",
    totalCompensationLakhs: 235.35,
    dbtStatus: "SUCCESSFUL",
    pftsRefNo: "051-501-2025-9012401",
    geoCoordinates: JSON.stringify({
      type: "Polygon",
      coordinates: [[[75.498, 31.438], [75.501, 31.438], [75.501, 31.441], [75.498, 31.441], [75.498, 31.438]]],
    }),
  },
  {
    id: "KHASRA-142-3-2",
    projectId: "NH-44-DELHI-AMRITSAR",
    khasraNo: "142/3/2",
    ownerName: "Harpreet Kaur",
    village: "Kartarpur",
    tehsil: "Jalandhar-II",
    district: "Jalandhar",
    state: "Punjab",
    areaHectares: 0.92,
    multiplier: 1.5,
    possessionStatus: "Pending",
    totalCompensationLakhs: 148.80,
    dbtStatus: "PENDING",
    pftsRefNo: "051-501-2025-9012402",
    geoCoordinates: JSON.stringify({
      type: "Polygon",
      coordinates: [[[75.502, 31.438], [75.505, 31.438], [75.505, 31.441], [75.502, 31.441], [75.502, 31.438]]],
    }),
  },
  {
    id: "KHASRA-MAHSR-1",
    projectId: "MAHSR-BULLET-TRAIN",
    khasraNo: "901/1",
    ownerName: "Ramesh Patel",
    village: "Navsari",
    tehsil: "Navsari",
    district: "Navsari",
    state: "Gujarat",
    areaHectares: 2.15,
    multiplier: 2.0,
    possessionStatus: "Possession Handed Over",
    totalCompensationLakhs: 450.00,
    dbtStatus: "SUCCESSFUL",
    pftsRefNo: "051-501-2025-9012499",
    geoCoordinates: JSON.stringify({
      type: "Polygon",
      coordinates: [[[72.952, 20.948], [72.955, 20.948], [72.955, 20.951], [72.952, 20.951], [72.952, 20.948]]],
    }),
  },
];

export const SEED_OBJECTIONS: Objection[] = [
  {
    id: "OBJ-101",
    projectId: "NH-44-DELHI-AMRITSAR",
    khasraNo: "142/3/1",
    complainantName: "Dr. Amrit Lal Meena, IAS",
    mobileNumber: "+91 94172-88712",
    category: "Valuation & Solatium Discrepancy",
    detailedGrounds: "Circle rate calculation omitted commercial roadside frontage multiplier.",
    status: "Pending",
    createdAt: new Date().toISOString(),
  },
];

export const SEED_AWARDS: Award[] = [
  {
    id: "AWD-142-3-1",
    parcelId: "KHASRA-142-3-1",
    khasraNo: "142/3/1",
    marketRateSec26: 104.60,
    solatiumSec30: 104.60,
    interestSec34: 26.15,
    totalAwardAmount: 235.35,
    determinedDate: "2025-08-15",
  },
];
